#ifndef PROTOBUF_PARSER_PROTOBUF_PARSER_BUILDERS_DIRECTORY_BUILDER_HPP_
#define PROTOBUF_PARSER_PROTOBUF_PARSER_BUILDERS_DIRECTORY_BUILDER_HPP_

namespace protobuf_parser {
namespace builders {

class DirectoryBuilder {};

}
}

#endif  // PROTOBUF_PARSER_PROTOBUF_PARSER_BUILDERS_DIRECTORY_BUILDER_HPP_
