#ifndef PROTOBUF_PARSER_PROTOBUF_PARSER_BUILDERS_PACKAGE_BUILDER_HPP_
#define PROTOBUF_PARSER_PROTOBUF_PARSER_BUILDERS_PACKAGE_BUILDER_HPP_

namespace protobuf_parser {
namespace builders {

class PackageBuilder {};

}
}

#endif  // PROTOBUF_PARSER_PROTOBUF_PARSER_BUILDERS_PACKAGE_BUILDER_HPP_
