//
// Created by hiddenst on 09.04.2021.
//

#ifndef PROTOBUF_PARSER_PROTOBUF_PARSER_STUB_MULTIPLE_ERROR_COLLECTOR_HPP_
#define PROTOBUF_PARSER_PROTOBUF_PARSER_STUB_MULTIPLE_ERROR_COLLECTOR_HPP_



class StubMultipleErrorCollector {

};



#endif //PROTOBUF_PARSER_PROTOBUF_PARSER_STUB_MULTIPLE_ERROR_COLLECTOR_HPP_
