#ifndef PROTOBUF_PARSER_PROTOBUF_PARSER_ITERATOR_DIRECTORY_ITERATOR_HPP_
#define PROTOBUF_PARSER_PROTOBUF_PARSER_ITERATOR_DIRECTORY_ITERATOR_HPP_

namespace protobuf_parser {
namespace iterator {

class DirectoryIterator {};

}
}

#endif  // PROTOBUF_PARSER_PROTOBUF_PARSER_ITERATOR_DIRECTORY_ITERATOR_HPP_
