#ifndef PROTOBUF_PARSER_PROTOBUF_PARSER_ITERATOR_PACKAGE_ITERATOR_HPP_
#define PROTOBUF_PARSER_PROTOBUF_PARSER_ITERATOR_PACKAGE_ITERATOR_HPP_

namespace protobuf_parser {
namespace iterator {

class PackageIterator {};

}
}

#endif  // PROTOBUF_PARSER_PROTOBUF_PARSER_ITERATOR_PACKAGE_ITERATOR_HPP_
